# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-04 15:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180604_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email1',
            field=models.CharField(default='Not Available', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 4, 15, 37, 20, 388860), null=True),
        ),
    ]
