# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-05 03:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180604_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_per_day', models.IntegerField(default=0)),
                ('users_per_week', models.IntegerField(default=0)),
                ('users_per_month', models.IntegerField(default=0)),
                ('api_per_day', models.IntegerField(default=0)),
                ('api_per_week', models.IntegerField(default=0)),
                ('api_per_month', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 5, 3, 48, 30, 486397), null=True),
        ),
    ]
